### ISSUE TITLE
Doc broken @ supermarket

### ISSUE THREAD

**Issue by doertedev** [jarosser06/chef-sysdig#5]
Oy. I tend to see this quite often: does the supermarket have problems parsing markdown? Every now and then there are descriptions with tables around. Do you know something about that? 

Greetings from germany, the cookbook works well!

**Comment by jarosser06** [comment]
Hey.  I'm not sure I have seen it break before.  I'll see if I can get it cleaned up on supermarket.

Glad to hear :)
